### ISSUE TITLE
Knit to reproducr_manuscript not working with new RStudio - needs older pandoc version

### ISSUE THREAD

**Issue by fewohlgemuth** [jschultecloos/reproducr#1]
Thank you Julia for your great package!
After updating RStudio knit to reproducr_manuscript does not work any more. I receive the error message connected to the lua scripts in ~/R/win-library/4.1/reproducr/rmarkdown/lua. I tried different solutions and it seems that RStudio comes with a new pandoc version 2.17.1.1 and author-info-blocks.lua does not work with this or newer pandoc version. 
My workaround was installing an older pandoc version (2.14) and specifying in my Rmd to use this version by rmarkdown::find_pandoc(version = '2.14').
Do you know which is the newest pandoc version that works with reproducr?

**Comment by tseidl** [comment]
I encountered the same issue, it seems that version 2.16.2 still works but version 2.17 doesn't. Just found this out by trial and error, perhaps that saves someone some time:) Don't have the time to figure out what changed but would be great if this could be fixed in the medium run, as I really enjoy this package!

**Comment by jschultecloos** [comment]
This should be fixed now, I have updated the respective Lua filters. Thanks for your interest in the package!
